name: Labeler
on: [push, pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        import os
        print("This is my first action")
      shell: python
